#!/usr/bin/env bash
#creatingfortheBestSolution
Best=1
while [ $Best -le 8 ]
do echo "Best School"
if [ $Best -eq 3 ]
then echo "bad luck"
elif [ $Best -eq 6 ]
then echo "good luck"
fi
((Best++))
done
