#!/usr/bin/env bash
x=1
while [ $x -le 20 ]
do
    case $x in
	4)
	        echo "bad luck from China"
		    ;;
	9)
	        echo "bad luck from japan"
		    ;;
	17)
	        echo "bad luck from italy"
		    ;;
	*)
	        echo "$x"
		    ;;
	esac
	(( x++ ))
    done
